### ISSUE TITLE
Possible bug in qzdiv() in gensys.jl

### ISSUE THREAD

**Issue by MattCocci** [spencerlyon2/Hobo.jl#1]
Noticed that line 248 of [gensys.jl](https://github.com/spencerlyon2/Hobo.jl/blob/master/src/gensys.jl) has the following line

```
    if (root[j, 2] > stake) || (root[j, 1] < -.1)
```

whereas the [qzdiv.m](http://sims.princeton.edu/yftp/gensys/mfiles/qzdiv.m) Matlab function has

```
      if (root(j,2) > stake | root(j,2) < -.1) 
```

We were getting errors until we changed the index in the second part of the Julia if-statement to match the Matlab version.

**Comment by sglyon** [comment]
Thank you for letting me know.

When you made the change, did it start working properly?

If so, would you (or whoever is working with this code) submit a pull request?

Thanks!

**Comment by sglyon** [comment]
Oh and I should also mention again that the `qzdiv` and `qzswitch` functions are both temporary. 

Eventually we should rely on the `ordschur` function that was [merged](https://github.com/JuliaLang/julia/pull/9701) into Base.LinAlg (module built in to Julia). This will not be available on 0.3.x (latest official release), but it should be fairly easy to do a temporary back port for our purposes until 0.4 is officially released.

**Comment by sglyon** [comment]
@pearlzli @MattCocci 

What do you think about  the following plan:
- Push changes (bug fixes) to gensys that are sitting in DSGE.jl to this repo
- Find a permanent and more visible home for that code under the QuantEcon umbrella
- Have the NYFRB and others who might want this feature access the code via its new home under QuantEcon

It is not a super high priority, but I did want to initiate the conversation.

**Comment by pearlzli** [comment]
Hi @spencerlyon2, sorry for the delay! I spoke with @micahjsmith yesterday about this, and we're definitely on board. I can fork Hobo.jl, change the call to `qzdiv` to `ordschur`, and submit a pull request. Then once you move `gensys` to QuantEcon, we'll be happy to use it through the QuantEcon package.

**Comment by sglyon** [comment]
That's great, thank you very much.

Looking forward to that!
